### PR TITLE
Add way to use the last used size

### PR DESCRIPTION
**Pull request by orioltf**
Proposal to solve #7 by adding a new relative keyword: `current`

### CODE REVIEW

**Comment by meodai** [comment]
I like the idea! Can you npm run build though?

**Comment by orioltf** [comment]
Yes I can, and travis didn't fail either (see below "Show all checks")

screen shot 2017-09-04 at 10 56 27

**Comment by orioltf** [comment]
dist also updated :-P

**Comment by meodai** [comment]
@orioltf thanks for you contribution!

**Comment by orioltf** [comment]
Would you please mind bumping up the version so that I can do a common package installation? The current release points to a commit from 29.03.2017. :) Thanks!

**Comment by meodai** [comment]
@orioltf I did its not 1.3.2 As soon as the test and readme will be covered it will be 1.3.3 i guess ;)

**Pull request merged**
